"""Fixed relationship1 

Revision ID: 00f256cd79a0
Revises: 61e5aeaff11f
Create Date: 2022-06-20 00:34:23.254304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00f256cd79a0'
down_revision = '61e5aeaff11f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'post', 'users', ['user_id'], ['id'])
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'post', type_='foreignkey')
    # ### end Alembic commands ###
