"""Fixed relationship

Revision ID: 61e5aeaff11f
Revises: 105b661e12c2
Create Date: 2022-06-20 00:16:20.826981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61e5aeaff11f'
down_revision = '105b661e12c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'post', 'users', ['user_id'], ['id'])
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'post', type_='foreignkey')
    # ### end Alembic commands ###
